spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs6400_fa21_team1
    username: root
    password: Zqf19980513
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true